services:
  hub:
    image: selenium/hub
      #    ports:
      #    - 4444:4444
  chrome:
    image: selenium/node-chrome
    depends_on:
    - hub
    shm_size: '2g'
    deploy:
      replicas: 1
    env_file: .env
  firefox:
    image: selenium/node-firefox
    depends_on:
    - hub
    shm_size: '2g'
    deploy:
      replicas: 1
    env_file: .env
